name: "Code review using LLM"
description: "Github action for code review using LLM. Supports Gemini for now, add GEMINI_API_KEY in secrets."
author: "Koushik Mondal"
branding:
  icon: "airplay"
  color: "orange"

inputs:
  gh-token:
    description: "The Github token for authentication."
    required: true
  code-change:
    description: "Code changes for review."
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
